image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - name: install cypress to workspace
    init: |
      npm install
      npx cypress install
  - name: run chrome tests
    command: |
      gp sync-done first-run && yes | npx cypress run --browser chrome
  - name: open cypress application
    command: |
      gp sync-await first-run && gp await-port 6080 && npx cypress open
